### ISSUE TITLE
Incorrect null method in NavBar and Welcome authButtonMethod's components.

### ISSUE THREAD

**Issue by Krak86** [microsoftgraph/msgraph-training-reactspa#1]
In the [https://docs.microsoft.com/en-us/graph/tutorials/react?tutorial-step=1](url) tutorial's step the `authButtonMethod` method is missing in the App.js file. Here is `null `and it doesn't work.
According the github code it should be `authButtonMethod={this.state.isAuthenticated ? this.logout.bind(this) : this.login.bind(this)}` in `NavBar` component, and `authButtonMethod={this.login.bind(this)} `in the `Welcome` (both in render method). 

Can you please update the tutorial to correct code, otherwise it takes longer than copy paste and run solution!

**Comment by jasonjoh** [comment]
Good catch! You should actually update it in a further step (https://docs.microsoft.com/en-us/graph/tutorials/react?tutorial-step=3), but that was omitted. I'll get that corrected.
