### ISSUE TITLE
Does not work for 2 different accounts I've tried, personal and business.

### ISSUE THREAD

**Issue by ian** [microsoftgraph/msgraph-training-reactspa#24]
![Screen Shot 2019-12-02 at 10 09 12 PM](https://user-images.githubusercontent.com/19853/70019860-68eab280-1550-11ea-9ce5-a6905038797d.png)

Interestingly enough, it's trying to hit a URL with /undefined on the end of it.  Can't seem to figure out where this is being generated but it doesn't look like it's in the app.

**Comment by jasonjoh** [comment]
@ian what version of MSAL do you have installed? I'm working my way through the tutorials to update dependencies and change code if needed, I can take a look at this one next to see if I reproduce what you're seeing.

**Comment by ian** [comment]
```
"msal": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/msal/-/msal-1.1.3.tgz",
      "integrity": "sha512-cdShb+N1H3OyR1y46ij6OO7QzeqC6BxrbrNcouS4JBrr1+DnZ55TumxQKEzWmTXHvsbsuz5PCyXZl812Un8L9g==",
      "requires": {
        "tslib": "^1.9.3"
      }
    },
```

**Comment by jasonjoh** [comment]
This issue on the MSAL repo looks pertinent: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1009

**Comment by jasonjoh** [comment]
I'm not sure if this matches what you're seeing, but I was able to get that error by waiting an hour after logging in and then trying to view the calendar. Your screenshot seems to indicate you get it right at login, so we may be looking at different issues.

In my case I get the following errors in the console (using Edge Dev). The browser is blocking the iFrame's attempt to issue the token request.

> Unsafe JavaScript attempt to initiate navigation for frame with origin 'http://localhost:3000' from frame with URL 'https://login.microsoftonline.com/7f761ab7-d03f-40fa-97f4-749ff48f9054/oauth2/v2.0/authorize?response_type=token&scope=user.read%20calendars.read%20openid%20profile&client_id=759abe11-2b97-4651-9988-7a5778e2667c&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcalendar&state=e91f8d19-b610-483e-be67-cfa37f7cf3cf&nonce=5c1c57c6-2489-480d-970d-e3a6def28546&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.1.3&login_hint=MeganB%40M365x930361.OnMicrosoft.com&login_req=2b68bf15-bc0b-4302-99fb-a1161154e1ef&domain_req=7f761ab7-d03f-40fa-97f4-749ff48f9054&domain_hint=organizations&client-request-id=51bb74ff-af70-45be-a6d4-741f8ab965f3&prompt=none'. The frame attempting navigation is targeting its top-level window, but is neither same-origin with its target nor has it received a user gesture. See https://www.chromestatus.com/features/5851021045661696.

**Comment by jasonjoh** [comment]
@ian I just merged a change to fix the error that I was running into on refresh. However I'm not convinced it's the same issue you're seeing. Can you try the updated code and see if it helps? If not, can you describe exactly when you see this error?

**Comment by ian** [comment]
Hey @jasonjoh just tried the demos, seems like a lot of new stuff got added.  01 doesn't do anything when I click the login button but 02 works perfectly, auth window opens and logs in and the header changes.  Seems like whatever was happening before isn't happening now.  Not sure what's up with 01 example however.

**Comment by jasonjoh** [comment]
The 01 demo is just UI basically (up through completing https://docs.microsoft.com/graph/tutorials/react?tutorial-step=1). It can be used to "short-cut" the tutorial for demo purposes if you just want to start from https://docs.microsoft.com/graph/tutorials/react?tutorial-step=2
