### ISSUE TITLE
Create React App npm commands out of date

### ISSUE THREAD

**Issue by Vartazian147** [microsoftgraph/msgraph-training-reactspa#29]
![image](https://user-images.githubusercontent.com/51330887/72644569-53ceb500-393f-11ea-9835-f84e685b25c5.png)

As a backend developer, not knowing much at all about react, I followed the above commands, and it only installed packages, but no code. With a bit of googling, I found  that it should be:

npx create-react-app graph-tutorial
cd graph-tutorial
npm start

![image](https://user-images.githubusercontent.com/51330887/72644834-043cb900-3940-11ea-9881-56f5ec1c7e6d.png)

https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

**Comment by jasonjoh** [comment]
Thanks! I will update that as it's now the preferred method, but the older method should have also worked. `npm install g' installs a package globally to your machine, and then you can run it with the `create-react-app` command. `npx create-react-app` basically skips the requirement of installing the `create-react-app` on your machine.

**Comment by jasonjoh** [comment]
Fixed in #37
