### ISSUE TITLE
Link to complete project incorrect

### ISSUE THREAD

**Issue by WConen** [microsoftgraph/msgraph-training-reactspa#3]
Nice tutorial, thanks!

The link to the complete project in (near the bottom)

https://github.com/microsoftgraph/msgraph-training-reactspa/README.md

seems to be incorrect, it should probably be

https://github.com/microsoftgraph/msgraph-training-reactspa/tree/master/demos/03-add-msgraph

instead of 

https://github.com/microsoftgraph/msgraph-training-reactspa/blob/master/Demos/03-add-msgraph

**Comment by jasonjoh** [comment]
Thanks @WConen, I'm glad you liked it! I'll get those links fixed.
