### ISSUE TITLE
Typescript support for Create React App Samples

### ISSUE THREAD

**Issue by AsishP** [microsoftgraph/msgraph-training-reactspa#30]
Hi, This project really helped to start with a react app for the graph MSAL library, however working through it found that it is missing typescript which is my preference. Hence, updated my copy to Typescript and is working now.  I am interested to make a contribution to this project with the typescript version of the code. I already have the code updated into my git fork, if Ok, will submit a PR. Please let me know

**Comment by jasonjoh** [comment]
I would definitely be interested! I'd need to see how this impacts the corresponding tutorial at https://docs.microsoft.com/graph/tutorials/react, but I think it would be a good change.

**Comment by AsishP** [comment]
Thanks, will submit a PR soon

Yeah, I am also hoping that this would be a helpful starting point for those using Typescript in their projects. Currently, I have done only one of the projects (add-msgraph) but if we feel like, I can update the other two with Typescript. 

For training content, happy to assist in any way. Below are high level steps I did to update the reactjs solution of (03-add-msgraph) to typescript version (04-add-msgraph-ts)

1. Ran the below command to install typescript in the react-app solution
2. `npm install --save typescript @types/node @types/react @types/react-dom @types/jest @types/reactstrap`. 
(tsconfig.ts file is automatically created)
3. Renamed files to .ts (for classes only) and .tsx (for components)
4. Created a class UserAgent.ts for UserAgentApplication as window.msal was not recognised as a global variable. 
5. Provided type declarations, props and state interfaces as typescript needs the declarations
6. Update method declarations for props wherever needed.
7. Create a Config.ts file and export the app details for use.

Please let me know if there are any queries.

**Comment by jasonjoh** [comment]
@AsishP thanks for the pull request. I actually refactored the structure of this repo and recreated the project from scratch using TypeScript. See #37

**Comment by ajzeigert** [comment]
Is the non-typescript version of this tutorial/source code available somewhere? Not everybody uses Typescript...

**Comment by jasonjoh** [comment]
@ajzeigert thanks for the feedback. Older versions of this tutorial are JS/JSX, but there are no plans to maintain a non-TypeScript version going forward. The last commit that was not TypeScript is here: https://github.com/microsoftgraph/msgraph-training-reactspa/tree/ccbd448e221209103e8c78ebdf8171e5631d22f4

We do have non-React JavaScript tutorial at https://docs.microsoft.com/graph/tutorials/javascript which shows doing these same actions using the Graph SDK from JavaScript.
