### ISSUE TITLE
AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. 

### ISSUE THREAD

**Issue by stubclan** [microsoftgraph/msgraph-training-reactspa#32]
I have narrowed this issue with the following issue but not sure how would I be able to fix this.

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/733

If anyone has any idea for a fix please let me know!!

**Comment by jasonjoh** [comment]
@stubclan when do you get this error? I cannot reproduce it with the existing code. I'm in the process of refreshing the tutorial and I've refactored the auth code quite a bit, and I don't reproduce it there either :).

Can you give the code in https://github.com/microsoftgraph/msgraph-training-reactspa/tree/refresh-tutorial and see if you still have this problem?
