### ISSUE TITLE
AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation

### ISSUE THREAD

**Issue by mmushatt** [microsoftgraph/msgraph-training-reactspa#35]
You will receive a insufficient permissions error when you execute this sample using the scopes in the **Config.js** file.  You need to provide the scopes correctly for a v2 App.

**Config.js**

   _scopes: [
    'user.read',
    'calendars.read'
  ]_

**Should read:**

  _scopes: [
    'https://graph.microsoft.com/user.read',
    'https://graph.microsoft.com/calendars.read'
  ]_

After making this modification, the React App successfully retrieved the user's profile for my B2C Tenant.

**Comment by jasonjoh** [comment]
That may be a B2C-specific thing, as those scopes are perfectly fine with a v2 app. I'll check with the Identity team to confirm.

**Comment by mmushatt** [comment]
I have it working within my sample after I made the necessary scope modifications.

**Comment by gato-negro** [comment]
Have the same issue. Any news on this?

**Comment by jasonjoh** [comment]
@gato-negro did you change the scopes as described?

**Comment by gato-negro** [comment]
@jasonjoh  The problem in my case was that user_impersonation scope needed also grant admin consent in the azure portal in the app registration of the web app consuming the web api. 
I thought this was not mandatory for this scope and i did not see a warning about it.
Anyway, it is working now. Thanks

**Comment by jasonjoh** [comment]
Please see the comment on #36 with my findings from the Microsoft Identity team.
