### ISSUE TITLE
response_type 'id_token' is not enabled for the application

### ISSUE THREAD

**Issue by FlyRocketDrones** [microsoftgraph/msgraph-training-reactspa#39]
When I enter my clientid and scopes, I get this.

Full error message is:
Message: AADSTS700054: response_type 'id_token' is not enabled for the application.

**Comment by jasonjoh** [comment]
Ok, that's a problem with the app registration in the Azure portal. Step 5 on [this page](https://docs.microsoft.com/graph/tutorials/react?tutorial-step=2) should fix you up.

Did you download the code via the [quick-start page](https://developer.microsoft.com/graph/quick-start?platform=option-react) by chance?

**Comment by FlyRocketDrones** [comment]
I don't have a SPA app, I have a full blown app. I am not recommended to allow implicit...

**Comment by jasonjoh** [comment]
Oh ok. This isn't really a support channel for Azure auth, but I'll try to give some information that might be helpful.

This sample is a SPA app and needs implicit. The auth library used here (msal.js) only does the implicit flow. There is another version of msal.js (2.x) being developed to support auth code flow, but it isn't released yet.

Your error indicates that you're requesting an ID token during the auth phase, and you haven't enabled ID tokens for implicit on your app registration. [Open ID Connect](https://docs.microsoft.com/azure/active-directory/develop/v2-protocols-oidc) for example requests the ID token during auth. You'll either need to change your code to not request an ID token during auth, or enable it on the app registration.

**Comment by FlyRocketDrones** [comment]
Makes sense. Thank you. I have an existing implementation and, interested to see other implementations to see where I can improve mine that's why I wanted to take a look at it. Thank you for the help!
