### ISSUE TITLE
Typescript 3.9 Error

### ISSUE THREAD

**Issue by semasdev** [microsoftgraph/msgraph-training-reactspa#41]
C:/Users/..../Documents/nodejs/react/graphtuto/src/AuthProvider.tsx
TypeScript error in C:/Users/.../Documents/nodejs/react/graphtuto/src/AuthProvider.tsx(74,11):
'error' is specified more than once, so this usage will be overwritten.  TS2783

```
    72 |       return (
    73 |         <WrappedComponent
  > 74 |           error={this.state.error}
       |           ^
    75 |           isAuthenticated={this.state.isAuthenticated}
    76 |           user={this.state.user}
    77 |           login={() => this.login()}
```

**Comment by jasonjoh** [comment]
Thanks @semasdev. I wrote this with Typescript 3.7.2, so there may have been something that changed between versions. I'll add this to my investigation backlog.

**Comment by semasdev** [comment]
It works fine up to version 3.8.3 and there are some issues in the typescript repo relating to version 3.9 with this kind of error. [microsoft/TypeScript #37613](https://github.com.cnpmjs.org/microsoft/TypeScript/issues/37613#issue-588053097)

**Comment by semasdev** [comment]
Removing the lines
```
error={this.state.error}
isAuthenticated={this.state.isAuthenticated}
user={this.state.user}
```
or 
```
{...this.props}
{...this.state}
```
from AuthProvider.tsx
```
...
<WrappedComponent
          error={this.state.error}
          isAuthenticated={this.state.isAuthenticated}
          user={this.state.user}
          login={() => this.login()}
          logout={() => this.logout()}
          getAccessToken={(scopes: string[]) => this.getAccessToken(scopes)}
          setError={(message: string, debug: string) =>
            this.setErrorMessage(message, debug)
          }
          {...this.props}
          {...this.state}
        />
...
```
will solve this problem
