### ISSUE TITLE
ClientAuthError - User Cancelled when running the app in Edge, works fine in Chrome

### ISSUE THREAD

**Issue by Alexp2019** [microsoftgraph/msgraph-training-reactspa#43]
Hi,

When running the application in Edge I receive the following error:

![image](https://user-images.githubusercontent.com/38928645/82869413-8cc40980-9f71-11ea-8008-34b7ba7d0054.png)

This happens when clicking 'Click here to sign in' as soon as the popup opens to, the error appears. 

If I attempt to continue signing in, after entering my password I get redirected to the home page within the popped up window:

![image](https://user-images.githubusercontent.com/38928645/82869811-3a371d00-9f72-11ea-94a2-68df7e5fcb4e.png)

When running in chrome, the app works perfectly.

Thanks!

**Comment by jasonjoh** [comment]
Thanks for the report. From the screenshots that looks like Edge Legacy, not the new Edge. Is that correct? Are you able to update Edge?

**Comment by Alexp2019** [comment]
Hi @jasonjoh Thanks for the response - I've just downloaded the new Edge and it works perfectly. Do you know if there's an auth workaround for Legacy edge?

**Comment by jasonjoh** [comment]
I don't. Unfortunately I'm short on machines with Legacy Edge installed, so I'm not able to test this to see if I can reproduce it. There are some notes about IE/Edge on the MSAL.js GitHub repository, but I'm not sure if they would solve this particular problem. https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser
