### ISSUE TITLE
Getting error "signature invalid" when trying to call my .net core api from this sample

### ISSUE THREAD

**Issue by jpro1001** [microsoftgraph/msgraph-training-reactspa#45]
Anyone know why I get the error "signature invalid" when trying to call my .net core api from this sample? I'm passing the access token in the header of the fetch() like other documents have suggested. I created a Azure app registration for my API and exposed the api etc. However, something is wrong with token or how I'm trying to validate it on my .net core api. The api works fine if I disable the [authorize] attribute on my class. Any suggestions would be greatly appreciated as I am suck.

.net core api startup.cs snippet:

services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

react spa snippet:
// Get the user's access token
        var accessToken = await this.props.getAccessToken(config.scopes);
        
        const startDateEncoded = encodeURIComponent('2018-02-01');
        const endDateEncoded = encodeURIComponent('2018-02-07');
          debugger;
        const response = await fetch(`https://localhost:44307/api/Amounts?StartDate=${startDateEncoded}&endDate=${endDateEncoded}`,{
            headers: !accessToken ? {} : { 'Authorization': `Bearer ${accessToken}`}
        }
        );

**Comment by jasonjoh** [comment]
Hi @jpro1001 this is beyond the scope of this sample. I'm going to close this as an issue. Off the top of my head, you can't use an access token for Graph (the `aud` parameter inside the token is set to `https://graph.microsoft.com`) to access any other API, including your own. You should be getting an access token for scopes defined by your API. The whole process is outlined in https://docs.microsoft.com/azure/api-management/api-management-howto-protect-backend-with-aad.
