### ISSUE TITLE
Multiple Authorities Error

### ISSUE THREAD

**Issue by TK-Asaba** [microsoftgraph/msgraph-training-reactspa#46]
Hi

As I tried sin-in according to tutorial, I saw the error "Multiple Authorities" as below screen and couldn't log in successfully.

<img width="585" alt="キャプチャ" src="https://user-images.githubusercontent.com/67736742/86420720-6cc2fb00-bd12-11ea-856a-6e4d44752f6d.PNG">

I tested several times with MS accounts (private and company) on browsers (chrome, edge), sometimes I could login without error. But after sign-out and sing-in again, the error message comes again.
How should I do for solve this issue?

**Comment by jasonjoh** [comment]
Could you screenshot your Azure AD portal app registration, specifically the **Authentication** page? Also, do you know what line of code is throwing this error?
