### ISSUE TITLE
Single Tenant, Organization only

### ISSUE THREAD

**Issue by ingimar-eyfjord** [microsoftgraph/msgraph-training-reactspa#47]
Hello, how would I go about configuring this for single-tenant purposes?

Currently, this training is for multi-tenant use, all users allowed. I wish to restrict my app to only my organization. Is there a different node package that needs to be used instead of msal?

Best regards.
Ingimar

**Comment by jasonjoh** [comment]
No, no other package required. What you'd need to do is:

- When registering the application in the Azure portal, choose the "My organization only" option.
- Change how you initialize the `UserAgentApplication` [here](https://github.com/microsoftgraph/msgraph-training-reactspa/blob/22d0a1577240c2ebc6c337a4cc3bafd33552c1c0/demo/graph-tutorial/src/AuthProvider.tsx#L38) to include the `authority` property set to `https://login.microsoftonline.com/<tenant>`, where `<tenant>` is your tenant ID. See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications#configuration-options
