### ISSUE TITLE
403 Error - Access token is empty

### ISSUE THREAD

**Issue by andatt** [microsoftgraph/msgraph-training-reactspa#54]
I am just trying to run the code with no changes from tutorial but keep getting this error when user authenticates:

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2020-09-11T11:21:34",
      "request-id": "4f00c76f-d4dc-465e-889a-d81dfa04969f",
      "client-request-id": "4f00c76f-d4dc-465e-889a-d81dfa04969f"
    }
  }
}
```

When I log the code output I can see there is in fact an access token which is passed into `getAuthenticatedClient`as expected. Any idea what's going on?

Thanks

**Comment by jasonjoh** [comment]
No, I'm sorry. You can see the Graph request if you use developer tools in your browser and go to the Network tab. From there you should be able to find what value is going in the `Authorization` header.
