### ISSUE TITLE
Code refrences are broken in tutorial

### ISSUE THREAD

**Issue by Freysi21** [microsoftgraph/msgraph-training-reactspa#55]
In
https://github.com/microsoftgraph/msgraph-training-reactspa/blob/main/tutorial/02-create-app.md
The code refrences to graph-tutorial are broken.

**Comment by Freysi21** [comment]
code Moment import missing from
https://github.com/microsoftgraph/msgraph-training-reactspa/blob/main/tutorial/05-add-ms-graph.md
should be
import moment, {Moment} from 'moment-timezone';

**Comment by jasonjoh** [comment]
Thanks for catching that @Freysi21! I'll fix the error in 05-add-ms-graph.md. Can you point me to the error in 02-create-app.md?
