### ISSUE TITLE
https://docs.microsoft.com/en-us/graph/tutorials/react?tutorial-step=3 is not building

### ISSUE THREAD

**Issue by jrutanen** [microsoftgraph/msgraph-training-reactspa#59]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

There is a mistake in the tutorial page for the AuthProvider.tsx render function.

    render() {
      return <WrappedComponent
        error = { this.state.error }
        isAuthenticated = { this.state.isAuthenticated }
        user = { this.state.user }
        login = { () => this.login() }
        logout = { () => this.logout() }
        getAccessToken = { (scopes: string[]) => this.getAccessToken(scopes)}
        setError = { (message: string, debug: string) => this.setErrorMessage(message, debug)}
        {...this.props} {...this.state} />;

-> {...this.state} is causing build error, this code is already fixed in the github, but should be updated in the tutorial

### To Reproduce

Copy the code from the tutorial until step 3 and try to run it. You'll get error message
F:/code/webDev/ReactMsGraph/LearningMsGraph/graph-tutorial/src/AuthProvider.tsx
TypeScript error in F:/code/webDev/ReactMsGraph/LearningMsGraph/graph-tutorial/src/AuthProvider.tsx(58,21):
'error' is specified more than once, so this usage will be overwritten.  TS2783

    56 |             render() {
    57 |                 return <WrappedComponent
  > 58 |                     error = { this.state.error }
       |                     ^
    59 |                     isAuthenticated = { this.state.isAuthenticated }
    60 |                     user = { this.state.user }
    61 |                     login = { () => this.login() }

1. Click on '....'
1. Scroll down to '....'
1. See error

### Expected behavior

I expected that the tutorial code would build without errors.

### Desktop

- OS: Windows 10
- Browser Chrome
- Version 86.0.4240.111

### Dependency versions

- Authentication library (MSAL, etc.) version:
- Graph library (Graph SDK, REST library, etc.) version:

**Comment by jasonjoh** [comment]
Thanks @jrutanen! Pushing a fix for this today.
