### ISSUE TITLE
Users with no time zone in mailbox settings causes app to fail

### ISSUE THREAD

**Issue by andrewliden** [microsoftgraph/msgraph-training-reactspa#60]
### Where did you get the code?

- Downloaded from GitHub
- Retrieved packages using the commands from the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Not all Microsoft accounts are supported by this demo, because not all user objects retrieved from GraphService's getUserDetails method have the mailboxSettings.timeZone property.  Accounts that do not have this property will hang whenever the user goes to the "Calendar" tab.

In my particular case, I was able to find a timeZone property that worked in:
mailboxSettings.workingHours.timeZone.name
in the JSON retrieved from getUserDetails() on the AuthProvider HOC.

### To Reproduce

1. Log in with an account which does not have the user.mailboxSettings.timeZone property
2. Click "Calendar"
3. The page will hang.

### Expected behavior

The demo should be able to retrieve timezone data for any kind of Microsoft account.
The demo should not hang for any valid Microsoft account.

### Desktop

- OS: Windows 10
- Browser: Chrome, Edge, Firefox
- Version: Latest

**Comment by jasonjoh** [comment]
What type of account did you encounter this for?

**Comment by andrewliden** [comment]
I encountered this issue on my work account, andrew.liden@federalmerchants.com.
Since I didn't originally create the account, I'm not sure of the specifics.

**Comment by jasonjoh** [comment]
Time zone *should* be set in your Outlook settings. You can check this by logging into your Exchange Online mailbox at outlook.office.com.

- Click the "gear" icon in the top right
- Select "General" in the left hand menu, then select "Language and time"

**Comment by andrewliden** [comment]
![image](https://user-images.githubusercontent.com/47042544/98171342-960cb700-1ebd-11eb-8dd1-f9aaf53ca835.png)

The time zone was correctly set, no changes were necessary.

**Comment by jasonjoh** [comment]
Interesting. Can you check in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) if the value doesn't come back? Just run a GET on `https://graph.microsoft.com/v1.0/me?$select=mailboxsettings`.

**Comment by andrewliden** [comment]
Here's what I get back, with some of the sensitive data expunged.  Interestingly, this time it did retrieve a timeZone.

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(mailboxSettings)/$entity",
    "id": "EXPUNGED",
    "mailboxSettings": {
        "archiveFolder": "EXPUNGED",
        "timeZone": "Eastern Standard Time",
        "delegateMeetingMessageDeliveryOptions": "sendToDelegateOnly",
        "dateFormat": "",
        "timeFormat": "",
        "automaticRepliesSetting": {
            "status": "disabled",
            "externalAudience": "all",
            "internalReplyMessage": "",
            "externalReplyMessage": "",
            "scheduledStartDateTime": {
                "dateTime": "2020-11-04T22:00:00.0000000",
                "timeZone": "UTC"
            },
            "scheduledEndDateTime": {
                "dateTime": "2020-11-05T22:00:00.0000000",
                "timeZone": "UTC"
            }
        },
        "language": {
            "locale": "en-US",
            "displayName": "English (United States)"
        },
        "workingHours": {
            "daysOfWeek": [
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday"
            ],
            "startTime": "08:00:00.0000000",
            "endTime": "17:00:00.0000000",
            "timeZone": {
                "name": "Eastern Standard Time"
            }
        }
    }
}

**Comment by jasonjoh** [comment]
Hrmm. Well I wonder if the act of accessing the settings somehow "fixed" it. AFAIK that setting can't be empty, but there may be some edge cases. I should probably just provide a default time zone there if it's undefined.

**Comment by andrewliden** [comment]
That sounds sensible.
