### ISSUE TITLE
Why in you're example you use require but not import 

### ISSUE THREAD

**Issue by Relaxe111** [microsoftgraph/msgraph-training-reactspa#63]
Hello, I am apologize if question is stupid  but I have hot discussions with my colleague about why in the [https://github.com/microsoftgraph/msgraph-training-reactspa/blob/main/demo/graph-tutorial/src/GraphService.ts#L9](https://github.com/microsoftgraph/msgraph-training-reactspa/blob/main/demo/graph-tutorial/src/GraphService.ts#L9) is used require  but not import? could someone explain this cause and why is not used es6 import instead? Would it not work with import?
Thank you in advance

**Comment by jasonjoh** [comment]
Using `import` should work fine - there's no reason not to use it here. It would be something like:

```
import * as graph from '@microsoft/microsoft-graph-client';
```

**Comment by Relaxe111** [comment]
Thank you )
